<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PersonajeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('personajes')->insert([
            [
                'id' => 1,
                'usuario_propietario' => 'admin',
                'nombre' => 'Astarion',
                'id_raza' => 1,
                'id_clase' => 9,
                'id_campaña' => 3,
                'estado' => 'Vivo',
                'nivel' => 1,
                'imagen' => 'Astarion.png',
                'car_fuerza' => 8,
                'car_destreza' => 17,
                'car_constitucion' => 14,
                'car_inteligencia' => 13,
                'car_sabiduria' => 13,
                'car_carisma' => 10,
                'id_transfondo' => 7,
                'id_alineamiento' => 8,
                'apariencia' => 'Astarion es un elfo vampiro, de estatura media, con una apariencia elegante y refinada. Tiene piel pálida, cabello oscuro y ojos intensos, a menudo con un brillo rojizo cuando se siente hambriento de sangre. Su presencia exhuda una mezcla de encanto seductor y aura siniestra.',
                'edad' => '239',
                'historia' => 'Astarion es un elfo vampiro que lleva siglos vagando por el mundo tras haber sido esclavizado por un poderoso maestro vampiro. Marcado por una existencia de cautiverio y sed de sangre, su vida cambió drásticamente cuando logró escapar de las garras de su opresor. A pesar de su libertad recién encontrada, Astarion lucha constantemente con su naturaleza vampírica, que lo empuja hacia actos oscuros, aunque en el fondo anhela redención y un propósito nuevo. Su elegancia y encanto ocultan un alma torturada que busca su lugar en un mundo que ve a los de su especie con miedo y desprecio. A lo largo de sus viajes, Astarion busca comprender mejor su existencia inmortal y, quizás, encontrar una manera de liberarse de su maldición vampírica.',
            ],
            [
                'id' => 2,
                'usuario_propietario' => 'admin',
                'nombre' => 'Corazon Sombrío',
                'id_raza' => 1,
                'id_clase' => 3,
                'id_campaña' => 3,
                'estado' => 'Vivo',
                'nivel' => 1,
                'imagen' => 'Shadowheart.png',
                'car_fuerza' => 12,
                'car_destreza' => 14,
                'car_constitucion' => 14,
                'car_inteligencia' => 10,
                'car_sabiduria' => 16,
                'car_carisma' => 10,
                'id_transfondo' => 1,
                'id_alineamiento' => 8,
                'apariencia' => 'La apariencia de Corazón Sombrío es la de un elfo alto y pálido, con cabello oscuro y ojos intensos, a menudo con un brillo rojizo. Viste ropas elegantes y refinadas, y su presencia exuda un aura de misterio y encanto. Sin embargo, su apariencia también puede ser un tanto siniestra, reflejando su naturaleza vampírica. Su rostro suele mostrar una sonrisa burlona y una mirada penetrante que revela su inteligencia y astucia.',
                'edad' => '40',
                'historia' => 'Corazón Sombrío es una clériga devota de Shar, la diosa de la oscuridad y los secretos. Criada en un templo lejano y enviado en una misión sagrada, su fe y lealtades son puestas a prueba cuando se encuentra atrapada en una lucha por la supervivencia tras la infestación de un parásito cerebral. Con recuerdos fragmentados y el conocimiento de que lleva un artefacto divino de poder incalculable, Shadowheart busca tanto aliados como respuestas en un mundo que le es hostil. Misteriosa y reservada, Shadowheart lucha por reconciliar sus enseñanzas y su fe con las realidades brutales del mundo fuera de su templo. Su viaje no solo es físico sino espiritual, buscando comprender su lugar en los designios de Shar, mientras navega por la complejidad de la amistad, la confianza y el poder. Su historia es una de descubrimiento personal, confrontación de secretos oscuros y búsqueda de redención o dominio en un mundo caótico.',
            ],
            [
                'id' => 3,
                'usuario_propietario' => 'admin',
                'nombre' => 'Gale',
                'id_raza' => 4,
                'id_clase' => 12,
                'id_campaña' => 3,
                'estado' => 'Vivo',
                'nivel' => 1,
                'imagen' => 'Gale.png',
                'car_fuerza' => 9,
                'car_destreza' => 14,
                'car_constitucion' => 15,
                'car_inteligencia' => 16,
                'car_sabiduria' => 11,
                'car_carisma' => 13,
                'id_transfondo' => 9,
                'id_alineamiento' => 1,
                'apariencia' => 'Gale es un mago de aspecto distinguido y refinado. Su cabello oscuro está cuidadosamente peinado hacia atrás, y su rostro está marcado por rasgos angulares y una mirada penetrante. Viste túnicas elegantes y bien ajustadas, adornadas con detalles intrincados y bordados finos. A pesar de su apariencia pulcra, su mirada refleja una profunda sabiduría y una determinación feroz. En su cintura, lleva un cinturón adornado con varios bolsillos y estuches que contienen componentes mágicos y pergaminos, listos para desatar poderosos hechizos en un instante. Su porte es erguido y seguro, mostrando una confianza que sugiere una larga experiencia en los caminos del conocimiento arcano y la aventura.',
                'edad' => '34',
                'historia' => 'Gale, un mago ambicioso con una sed insaciable por el conocimiento arcano, se aventuró más allá de los límites de la magia segura, buscando poder a través de artefactos prohibidos. Su obsesión lo llevó a Baldur\'s Gate, en medio de una crisis que amenazaba con desatar un mal antiguo. Uniéndose a un grupo de aventureros, Gale busca redimir sus acciones pasadas y detener la amenaza, luchando contra los secretos oscuros que lo acechan.',
            ],
            [
                'id' => 4,
                'usuario_propietario' => 'admin',
                'nombre' => 'Karlach',
                'id_raza' => 2,
                'id_clase' => 1,
                'id_campaña' => 3,
                'estado' => 'Vivo',
                'nivel' => 1,
                'imagen' => 'Karlach.png',
                'car_fuerza' => 15,
                'car_destreza' => 13,
                'car_constitucion' => 14,
                'car_inteligencia' => 9,
                'car_sabiduria' => 12,
                'car_carisma' => 12,
                'id_transfondo' => 10,
                'id_alineamiento' => 2,
                'apariencia' => 'Karlach es una guerrera de aspecto imponente y feroz. Con una estatura alta y musculosa, lleva una armadura de placas oscura y adornada con runas, que refleja su habilidad en combate y su aura de misterio. Su cabello oscuro y corto enmarca un rostro marcado por cicatrices de batalla, y su mirada fría y determinada revela una determinación inquebrantable. Empuña una gran espada con habilidad y confianza, lista para enfrentarse a cualquier desafío que se interponga en su camino.',
                'edad' => 'Indeterminada',
                'historia' => 'Karlach es una guerrera curtida en la batalla, cuya vida está marcada por el conflicto y la lucha. Nacida en las tierras fronterizas, creció en un ambiente de guerra constante y aprendió desde joven a defenderse por sí misma. Con el tiempo, se convirtió en una guerrera formidable, ganando reputación por su habilidad en combate y su determinación inquebrantable. A lo largo de los años, Karlach ha viajado por tierras lejanas, luchando en numerosas batallas y enfrentándose a enemigos mortales. Su vida está marcada por cicatrices de guerra y recuerdos dolorosos, pero también por momentos de coraje y victoria. Ahora, Karlach se encuentra en Baldur\'s Gate, buscando un nuevo propósito y una oportunidad para dejar atrás su pasado tumultuoso. Aunque su corazón está endurecido por las batallas que ha librado, aún conserva una chispa de esperanza de encontrar un destino digno y un futuro más brillante.',
            ],
            [
                'id' => 5,
                'usuario_propietario' => 'admin',
                'nombre' => 'Lae\'zel',
                'id_raza' => 5,
                'id_clase' => 5,
                'id_campaña' => 3,
                'estado' => 'Vivo',
                'nivel' => 1,
                'imagen' => 'Laezel.png',
                'car_fuerza' => 17,
                'car_destreza' => 13,
                'car_constitucion' => 14,
                'car_inteligencia' => 11,
                'car_sabiduria' => 12,
                'car_carisma' => 8,
                'id_transfondo' => 10,
                'id_alineamiento' => 4,
                'apariencia' => 'Lae\'Zel es una guerrera githyanki de aspecto feroz y distinguido. Con una estatura alta y esbelta, su piel pálida contrasta con su cabello blanco plateado, que cae en trenzas elaboradas alrededor de su cabeza. Sus ojos brillan con una intensidad penetrante, reflejando su determinación y orgullo. Viste una armadura ligera pero resistente, adornada con símbolos de su linaje y trofeos de batalla. En su mano empuña una espada larga githyanki con destreza y confianza, lista para enfrentarse a cualquier desafío con fiereza implacable.',
                'edad' => 'Indeterminada',
                'historia' => 'Lae\'Zel es una guerrera githyanki dedicada y feroz que se encuentra en una misión para destruir a los parásitos cerebrales y a sus huéspedes. Capturada y encerrada en un ataúd de nautiloide, busca desesperadamente una cura para su propia infección por un parásito cerebral. Su lealtad a su gente y su desdén por aquellos que considera inferiores definen su enfoque pragmático y a menudo impaciente hacia los demás.',
            ],
            [
                'id' => 6,
                'usuario_propietario' => 'admin',
                'nombre' => 'Wyll',
                'id_raza' => 4,
                'id_clase' => 11,
                'id_campaña' => 3,
                'estado' => 'Vivo',
                'nivel' => 1,
                'imagen' => 'Wyll.png',
                'car_fuerza' => 9,
                'car_destreza' => 13,
                'car_constitucion' => 15,
                'car_inteligencia' => 14,
                'car_sabiduria' => 11,
                'car_carisma' => 16,
                'id_transfondo' => 5,
                'id_alineamiento' => 3,
                'apariencia' => 'Wyll tiene el cabello castaño oscuro ordenado en hileras ordenadas con los lados recortados y una barba circular recortada que adorna su rostro. Su ojo derecho está hecho de una piedra enviadora, regalada por Mizora como reemplazo después de perder su ojo luchando contra los cultistas, y sirve como método para seguirlo. A pesar de las cicatrices que adornan su rostro, conserva un rostro juvenil y una mirada encantadora. Siempre viste ropas elegantes que complementan su estatura y figura esbelta, y lleva consigo un bastón mágico, símbolo de su poder y estatus como hechicero.',
                'edad' => '28',
                'historia' => 'Wyll, conocido entre la gente como "El Hoja Azul", es un renombrado héroe entre los habitantes de Baldur\'s Gate y más allá. Su fama se debe no solo a su carisma y atractivo, sino también a sus proezas mágicas y valentía inigualables. Antes de ganarse su título, Wyll hizo un pacto con un ser de otro mundo para obtener el poder necesario para proteger a los inocentes y buscar venganza contra los cultistas del Absoluto que destruyeron su vida. A pesar de su apariencia confiada y a veces arrogante, Wyll lucha con la carga de su pacto, temiendo que el precio de su poder eventualmente lo consumirá. Sin embargo, su determinación por hacer el bien y proteger a aquellos que no pueden hacerlo por sí mismos lo impulsa hacia adelante, enfrentándose a cualquier amenaza con coraje y determinación. En su viaje, Wyll busca derrotar a los cultistas del Absoluto, liberarse de su pacto arcano y asegurar su legado como un verdadero héroe, no solo uno construido por historias y rumores.',
            ]
        ]);

    }
}
